# Change these first
owner: akram-osg # Your GitHub organization or username, where this repository lives
repo: westside-watcher # The name of this repository

sites:
  - name: Westside Market
    url: https://www.westsidemarket.com
  - name: Westside Market (Odoo)
    url: https://app.westsidemarket.com
  - name: Westside Market (API)
    url: https://api.westsidemarket.com/v2/states
  - name: Westside Market (Members Portal)
    url: https://members.westsidemarket.com
  - name: Odoo Development
    url: https://development.westsidemarket.com
  - name: Odoo Staging
    url: https://staging.westsidemarket.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /westside-watcher/
  logoUrl: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkBUA_Wf5KFWG2Gc4encOu-ur4v3YoFWs_eQ&s
  name: Westside
  introTitle: "**Westside Market** System Status"
  introMessage: This status page shows uptime data for all Westside websites.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
